FROM python:3.10-slim

WORKDIR /app

COPY facade-service.py messages_pb2.py messages_pb2_grpc.py /app/

RUN pip install --no-cache-dir requests grpcio grpcio-tools flask protobuf

CMD ["python", "facade-service.py"]
