# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messages.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\x12\x08messages\"%\n\nLogRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03txt\x18\x02 \x01(\t\"\x1d\n\x0bLogResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"\x1f\n\x0bMessageList\x12\x10\n\x08messages\x18\x01 \x03(\t2\x82\x01\n\x0eLoggingService\x12\x39\n\nLogMessage\x12\x14.messages.LogRequest\x1a\x15.messages.LogResponse\x12\x35\n\x0bGetMessages\x12\x0f.messages.Empty\x1a\x15.messages.MessageListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGREQUEST']._serialized_start=28
  _globals['_LOGREQUEST']._serialized_end=65
  _globals['_LOGRESPONSE']._serialized_start=67
  _globals['_LOGRESPONSE']._serialized_end=96
  _globals['_EMPTY']._serialized_start=98
  _globals['_EMPTY']._serialized_end=105
  _globals['_MESSAGELIST']._serialized_start=107
  _globals['_MESSAGELIST']._serialized_end=138
  _globals['_LOGGINGSERVICE']._serialized_start=141
  _globals['_LOGGINGSERVICE']._serialized_end=271
# @@protoc_insertion_point(module_scope)
